In [1]:
import torch

if torch.cuda.is_available():
    x = torch.randn(3, 3, device='cuda')
    y = torch.matmul(x, x.T)
    print('CUDA device:', torch.cuda.get_device_name(0))
    print('Tensor device:', x.device)
    print('Matrix multiply result shape:', y.shape)
else:
    print('CUDA is not available in this notebook environment.')

CUDA device: NVIDIA GeForce MX350
Tensor device: cuda:0
Matrix multiply result shape: torch.Size([3, 3])

In [2]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)

PyTorch version: 2.5.1+cu121
CUDA available: True
GPU: NVIDIA GeForce MX350
CUDA version: 12.1

### Load PDFs

In [3]:
from pathlib import Path
from pypdf import PdfReader

PROJECT_DIR = Path.cwd().parent
DATA_DIR = PROJECT_DIR / "data" / "raw"

pdf_files = list(DATA_DIR.glob("*.pdf"))

print(f"Found {len(pdf_files)} PDF files:")

for pdf in pdf_files:
    print(f"- {pdf.name}")

Found 3 PDF files:
- Session 3 intro to ML.pdf
- Session 6 - Linear Regresssion.pdf
- Session 7 Ml -logistic regression.pdf

### Load & Inspect

In [4]:
from pypdf import PdfReader

documents = []

for pdf_path in pdf_files:
    reader = PdfReader(pdf_path)

    text = ""

    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"

    documents.append({
        "source": pdf_path.name,
        "pages": len(reader.pages),
        "text": text
    })

for doc in documents:
    print("=" * 80)
    print(f"Source: {doc['source']}")
    print(f"Pages: {doc['pages']}")
    print(f"Characters: {len(doc['text'])}")
    print("\nFirst 500 characters:")
    print(doc["text"][:500])

================================================================================
Source: Session 3 intro to ML.pdf
Pages: 40
Characters: 16413

First 500 characters:
Introduction to
Machine
Learning (ML)
Learning Objectives:
By the end of this session, you should:
• Understand the Core Fields of AI – Learn about Machine Learning
(ML), Deep Learning (DL), NLP, Computer Vision, Robotics, and
Generative Models.
• Differentiate Between AI Subfields – Recognize how ML, DL, NLP,
and Computer Vision contribute to AI advancements.
• Explore Real-World Applications of AI – Discover how AI is used in
self-driving cars, chatbots, precision agriculture, personal
================================================================================
Source: Session 6 - Linear Regresssion.pdf
Pages: 23
Characters: 2572

First 500 characters:
Machine
Learning
Session 6
Linear Regression
Presented By Eng : Mohamed Khaled
WHAT IS LINEAR REGRESSION?

WHAT IS LINEAR REGRESSION?

Our hypothesis function has the general form
• like the equation of a straight line
• create a function called 𝒉𝜽 that is trying to map
our input data (the 𝑥′𝑠) to our output data (the 𝑦′𝑠).
Linear Regression The Hypothesis Function
intercept and slope
Example
Interactive Visualization of Linear Regression (Demo )
Multiple variables (Features)
• Linear re
================================================================================
Source: Session 7 Ml -logistic regression.pdf
Pages: 40
Characters: 6761

First 500 characters:
Machine
Learning
Session
Logistic regression
Presented by Eng : Mohamed Khaled
Classification
Email: Spam / Non Spam
Online transactions: Fraud / Not Fraud
Tumor: Malignant / Benign ?
Tumor

Hypothesis

Interpreting hypothesis output

So if z is positive, g(z) is greater than 0.5
z = (θT x)
So when
θT x >= 0
Then hθ >= 0.5
• So what we've shown is that the hypothesis predicts
y = 1 when θT x >= 0
• The corollary of that when θT x <= 0 then the
hypothesis predicts y = 0
Let's use this to b

### Cleaning + Chunking ✂️

In [5]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=["\n\n", "\n", ". ", " ", ""]
)

chunks = []

for doc in documents:
    doc_chunks = text_splitter.split_text(doc["text"])

    for i, chunk in enumerate(doc_chunks):
        chunks.append({
            "text": chunk,
            "source": doc["source"],
            "chunk_id": i
        })

print(f"Total chunks: {len(chunks)}")

Total chunks: 45

In [6]:
for chunk in chunks[:5]:
    print("=" * 80)
    print(f"Source: {chunk['source']}")
    print(f"Chunk ID: {chunk['chunk_id']}")
    print(chunk["text"][:800])

================================================================================
Source: Session 3 intro to ML.pdf
Chunk ID: 0
Introduction to
Machine
Learning (ML)
Learning Objectives:
By the end of this session, you should:
• Understand the Core Fields of AI – Learn about Machine Learning
(ML), Deep Learning (DL), NLP, Computer Vision, Robotics, and
Generative Models.
• Differentiate Between AI Subfields – Recognize how ML, DL, NLP,
and Computer Vision contribute to AI advancements.
• Explore Real-World Applications of AI – Discover how AI is used in
self-driving cars, chatbots, precision agriculture, personal
assistants, and more.
• See the Connection Between AI Technologies – Understand how AI,
ML, DL, and Generative Models are interrelated and drive
innovation.
What is Artificial Intelligence (AI)?
Definition
Artificial Intelligence (AI) is the science of making machines
================================================================================
Source: Session 3 intro to ML.pdf
Chunk ID: 1
innovation.
What is Artificial Intelligence (AI)?
Definition
Artificial Intelligence (AI) is the science of making machines
think, learn, and act like humans.
It allows computers to perform tasks that require human
intelligence, such as recognizing speech, understanding
images, and making decisions.
Generative Models
Generative models are types of AI algorithms that generate new data,
mimicking the characteristics of the data they were trained on. These
models learn the underlying distribution of the data and use that
knowledge to create new samples, like images, text, or audio.
Example:
•GANs (Generative Adversarial Networks): Used to generate realistic
images from noise. For instance, GANs can generate photos of non-
================================================================================
Source: Session 3 intro to ML.pdf
Chunk ID: 2
Example:
•GANs (Generative Adversarial Networks): Used to generate realistic
images from noise. For instance, GANs can generate photos of non-
existent people that look very realistic (such as those on "This Person
Does Not Exist").
•GPT (Generative Pretrained Transformers): Can generate coherent text
based on a given prompt.
Precision Agriculture
Precision Agriculture refers to the use of AI and technology to optimize
farming practices, increase crop yields, reduce waste, and minimize
environmental impact.
•Example:
•Drones and Sensors: AI-driven drones monitor crop health, using
image recognition to detect diseases or pest infestations, allowing
farmers to take corrective actions earlier and more efficiently.
Chatbots
================================================================================
Source: Session 3 intro to ML.pdf
Chunk ID: 3
image recognition to detect diseases or pest infestations, allowing
farmers to take corrective actions earlier and more efficiently.
Chatbots
Chatbots are AI systems designed to interact with users through text or
voice. They can provide customer support, answer queries, and even
handle transactions.
Example:
•Customer Service Chatbots: Chatbots like ChatGPT or those used by
companies such as Amazon or banking apps that assist users with their
inquiries or issues.
Emotions Detection
Emotions detection uses AI to interpret human emotions based on facial
expressions, voice tone, body language, or other signals. It’s used in
applications like customer service, mental health care, and marketing.
Example:
•Emotion Recognition in Video Calls: Some AI systems can detect the
================================================================================
Source: Session 3 intro to ML.pdf
Chunk ID: 4
applications like customer service, mental health care, and marketing.
Example:
•Emotion Recognition in Video Calls: Some AI systems can detect the
emotional state of people during video conferences (e.g., detecting if
someone is frustrated or happy based on their facial expressions and
voice tone).
Robots
Robotics is the branch of AI that deals with creating robots—machines
capable of performing tasks that typically require human intervention.
AI enables robots to perform complex functions autonomously.
Example:
•Industrial Robots: Robots used in car manufacturing to perform
repetitive tasks like assembling parts. They learn and improve based
on experience and can operate in dynamic environments.
Autonomous Vehicles
Autonomous vehicles, also known as self-driving cars, use AI to

### Metadata + Embeddings

In [7]:
import torch
from sentence_transformers import SentenceTransformer

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device=device
)

print("Embedding model loaded!")

Device: cuda
Embedding model loaded!

### Generate Embeddings

In [8]:
texts = [chunk["text"] for chunk in chunks]

embeddings = embedding_model.encode(
    texts,
    batch_size=16,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Embeddings shape:", embeddings.shape)

Batches:   0%|          | 0/3 [00:00<?, ?it/s]

Embeddings shape: (45, 384)

### Create ChromaDB

In [9]:
import chromadb

VECTOR_DB_DIR = PROJECT_DIR / "backend" / "data" / "vector_store"

VECTOR_DB_DIR.mkdir(parents=True, exist_ok=True)

client = chromadb.PersistentClient(
    path=str(VECTOR_DB_DIR)
)

collection = client.get_or_create_collection(
    name="studymate_documents",
    metadata={"hnsw:space": "cosine"}
)

print("Chroma collection ready!")

Chroma collection ready!

### Store Chunks + Embeddings

In [10]:
collection.add(
    ids=[f"chunk_{i}" for i in range(len(chunks))],
    documents=texts,
    embeddings=embeddings.tolist(),
    metadatas=[
        {
            "source": chunk["source"],
            "chunk_id": chunk["chunk_id"]
        }
        for chunk in chunks
    ]
)

print("Stored chunks:", collection.count())

Stored chunks: 45

### Test Retrieval

In [11]:
query = "What is linear regression?"

query_embedding = embedding_model.encode(
    [query],
    normalize_embeddings=True
)[0]

results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

for i in range(3):
    print("=" * 80)
    print("Source:", results["metadatas"][0][i]["source"])
    print("Chunk ID:", results["metadatas"][0][i]["chunk_id"])
    print("Distance:", results["distances"][0][i])
    print(results["documents"][0][i][:800])

================================================================================
Source: Session 6 - Linear Regresssion.pdf
Chunk ID: 0
Distance: 0.18247240781784058
Machine
Learning
Session 6
Linear Regression
Presented By Eng : Mohamed Khaled
WHAT IS LINEAR REGRESSION?

WHAT IS LINEAR REGRESSION?
================================================================================
Source: Session 6 - Linear Regresssion.pdf
Chunk ID: 1
Distance: 0.4174213409423828
Our hypothesis function has the general form
• like the equation of a straight line
• create a function called 𝒉𝜽 that is trying to map
our input data (the 𝑥′𝑠) to our output data (the 𝑦′𝑠).
Linear Regression The Hypothesis Function
intercept and slope
Example
Interactive Visualization of Linear Regression (Demo )
Multiple variables (Features)
• Linear regression with multiple variables is also known as "multivariate linear regression".
Multiple variables (Features)
Interactive Visualization of Linear Regression (Demo )
Cost Function
• We can measure the accuracy of our hypothesis function by using a cost
function.
• This takes an average of all the results of the hypothesis with inputs from x's
compared to the actual output y's.
================================================================================
Source: Session 6 - Linear Regresssion.pdf
Chunk ID: 5
Distance: 0.491122305393219
validation, or test data (e.g., your y_test vs. y_pred). They help quantify prediction accuracy
and model fit. Below are the main evaluation metrics for linear regression, many of which
you referenced earlier (MSE, AMSE, R-squared).
1. Mean Squared Error (MSE)

In [12]:
def retrieve_documents(query, k=3):
    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=k
    )

    retrieved = []

    for i in range(len(results["documents"][0])):
        retrieved.append({
            "text": results["documents"][0][i],
            "source": results["metadatas"][0][i]["source"],
            "chunk_id": results["metadatas"][0][i]["chunk_id"],
            "distance": results["distances"][0][i]
        })

    return retrieved

In [13]:
retrieved = retrieve_documents(
    "What is the hypothesis function in linear regression?",
    k=3
)

for doc in retrieved:
    print("=" * 80)
    print("Source:", doc["source"])
    print("Distance:", doc["distance"])
    print(doc["text"][:500])

================================================================================
Source: Session 6 - Linear Regresssion.pdf
Distance: 0.26666587591171265
Our hypothesis function has the general form
• like the equation of a straight line
• create a function called 𝒉𝜽 that is trying to map
our input data (the 𝑥′𝑠) to our output data (the 𝑦′𝑠).
Linear Regression The Hypothesis Function
intercept and slope
Example
Interactive Visualization of Linear Regression (Demo )
Multiple variables (Features)
• Linear regression with multiple variables is also known as "multivariate linear regression".
Multiple variables (Features)
Interactive Visualizatio
================================================================================
Source: Session 6 - Linear Regresssion.pdf
Distance: 0.47825127840042114
Machine
Learning
Session 6
Linear Regression
Presented By Eng : Mohamed Khaled
WHAT IS LINEAR REGRESSION?

WHAT IS LINEAR REGRESSION?
================================================================================
Source: Session 7 Ml -logistic regression.pdf
Distance: 0.5863596200942993
Machine
Learning
Session
Logistic regression
Presented by Eng : Mohamed Khaled
Classification
Email: Spam / Non Spam
Online transactions: Fraud / Not Fraud
Tumor: Malignant / Benign ?
Tumor

Hypothesis

Interpreting hypothesis output

So if z is positive, g(z) is greater than 0.5
z = (θT x)
So when
θT x >= 0
Then hθ >= 0.5
• So what we've shown is that the hypothesis predicts
y = 1 when θT x >= 0
• The corollary of that when θT x <= 0 then the
hypothesis predicts y = 0
Let's use this to b

### : Grounded Generation

In [16]:
from ollama import chat

def build_context(retrieved_docs):
    context_parts = []

    for i, doc in enumerate(retrieved_docs, start=1):
        context_parts.append(
            f"[Source {i}: {doc['source']} | Chunk {doc['chunk_id']}]\n"
            f"{doc['text']}"
        )

    return "\n\n".join(context_parts)

In [17]:
def generate_answer(question, k=3):
    # Retrieve relevant documents
    retrieved_docs = retrieve_documents(question, k=k)

    # Build context from retrieved chunks
    context = build_context(retrieved_docs)

    prompt = f"""
You are StudyMate, a university study assistant.

Answer the student's question using ONLY the provided course material.

Rules:
1. Do not use outside knowledge.
2. Do not invent information.
3. If the answer is not available in the provided context, say:
"I couldn't find this information in the provided course materials."
4. Keep the answer clear and educational.
5. At the end, list the sources used.

COURSE MATERIAL:
{context}

STUDENT QUESTION:
{question}
"""

    response = chat(
        model="mistral",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"], retrieved_docs

In [18]:
answer, sources = generate_answer(
    "What is the hypothesis function in linear regression?"
)

print(answer)

 The hypothesis function in linear regression is a function that maps the input data (x's) to the output data (y's), taking the form of a straight line. It is denoted by 𝒉𝜽 and tries to replicate the relationship between the input variables and the output variable. In other words, it creates a model that best fits the data points in a linear way.

In the provided course material, it is mentioned that linear regression can handle multiple variables (features) as well.

[Source 1: Session 6 - Linear Regresssion.pdf | Chunk 1, Chunk 0]
[Source 2: Session 6 - Linear Regresssion.pdf | Chunk 0]

In [19]:
answer, sources = generate_answer(
    "What is logistic regression used for?"
)

print(answer)

 Logistic regression is used for binary classification problems, where the goal is to predict the probability of an event occurring or not, based on a set of input features. In the context provided, logistic regression is used to predict whether a student passes or fails an exam based on their study hours.

[Sources: Session 7 Ml -logistic regression.pdf | Chunk 6, Chunk 7]

In [20]:
answer, sources = generate_answer(
    "What is reinforcement learning?"
)


print(answer)

 Reinforcement Learning is a type of Machine Learning where the model learns by interacting with an environment and receiving rewards or penalties. This learning method allows the model to make decisions to maximize the total reward over time. Examples of applications include teaching robots to walk, AI playing games like Chess and Go, and training agents for navigation tasks. Algorithms for Reinforcement Learning include Q-Learning, Deep Q Networks (DQN), and Proximal Policy Optimization (PPO). [Source 1: Session 3 intro to ML.pdf | Chunk 11]

In [21]:
test_questions = [
    "What is linear regression?",
    "What is the hypothesis function in linear regression?",
    "What is the cost function?",
    "What is multiple linear regression?",
    "What is logistic regression?",
    "What is the sigmoid function?",
    "What is classification?",
    "What is the difference between linear regression and logistic regression?",
    "What is overfitting?",
    "What is reinforcement learning?"
]

for i, question in enumerate(test_questions, start=1):
    print("=" * 100)
    print(f"Question {i}: {question}")
    
    answer, sources = generate_answer(question)
    
    print("\nAnswer:")
    print(answer)

====================================================================================================
Question 1: What is linear regression?

Answer:
 Linear Regression is a statistical method used to establish a relationship between two variables. The hypothesis function in linear regression is designed to map input data (x's) to output data (y's), and it has the form of an equation for a straight line. This equation includes an intercept (also known as the bias) and a slope (also known as the weight). Linear regression can also handle multiple variables (features). To measure the accuracy of the hypothesis function, a cost function is used, which takes an average of all the results of the hypothesis with inputs from x's compared to the actual output y's.

Sources:
1. Session 6 - Linear Regression.pdf | Chunk 0, 1, 5
====================================================================================================
Question 2: What is the hypothesis function in linear regression?

Answer:
 The hypothesis function in linear regression is a function that attempts to map our input data (the x's) to our output data (the y's). It has the general form of a straight line equation and is represented as 𝒉𝜽. The hypothesis function for linear regression with multiple variables is also known as "multivariate linear regression."

In simpler terms, the hypothesis function in linear regression defines the relationship between the independent and dependent variables in the form of a straight line.

[Source 1: Session 6 - Linear Regresssion.pdf | Chunk 1]
[Source 2: Session 6 - Linear Regresssion.pdf | Chunk 0]
====================================================================================================
Question 3: What is the cost function?

Answer:
 The Cost function, also known as the loss function or objective function, measures how well the model's predictions align with the actual labels in the training data. It quantifies the error that the model needs to minimize during training to find the optimal parameters. [Source 3: Session 7 Ml -logistic regression.pdf | Chunk 3]

However, in the provided context, specific details about the cost function for logistic regression are not discussed. For Linear Regression, there are examples of Mean Squared Error (MSE) and Mean Absolute Error (MAE) cost functions mentioned, but not for logistic regression. [Source 1: Session 6 - Linear Regresssion.pdf | Chunk 3]

Sources:
1. Session 6 - Linear Regresssion.pdf
2. Session 7 Ml -logistic regression.pdf
====================================================================================================
Question 4: What is multiple linear regression?

Answer:
 Multiple linear regression is a type of linear regression that deals with multiple independent variables (also known as features). It is used to study the relationship between a dependent variable (output) and more than one independent variable (input). This is also known as "multivariate linear regression" (Source 2, Chunk 2).

In multiple linear regression, the hypothesis function is extended to include multiple independent variables. The function creates a model that predicts the dependent variable based on the combined effects of the independent variables (Source 2, Chunk 0).

Sources:
1. Session 6 - Linear Regresssion.pdf
2. Session 6 - Linear Regresssion.pdf
3. Session 6 - Linear Regresssion.pdf
====================================================================================================
Question 5: What is logistic regression?

Answer:
 Logistic regression is a statistical method used to predict probabilities and classify data. It involves training a model to output probabilities, using a sigmoid function (hθ​(x)). These probabilities can represent the likelihood of an event occurring, such as predicting whether a student passes or fails an exam based on their study hours. The decision boundary arises after training and shows where the model switches between classes (y=0 and y=1). In the provided example, if (x1 + x2 >= 3), the model predicts y = 1.

Sources:
1. Session 7 Ml -logistic regression.pdf | Chunk 6
2. Session 7 Ml -logistic regression.pdf | Chunk 2
3. Session 7 Ml -logistic regression.pdf | Chunk 7
====================================================================================================
Question 6: What is the sigmoid function?

Answer:
 The sigmoid function is a mathematical function used in logistic regression to map the output of a neural network to a probability value between 0 and 1. It is defined as:

g(z) = 1 / (1 + e^-z)

where z is the input to the function. The sigmoid function squashes the output into a range between 0 and 1, allowing us to interpret the output as a probability.

In the context of logistic regression, the hypothesis function hθ(x) is a linear combination of features multiplied by their respective parameters, and the sigmoid function is applied to the result to obtain the predicted probability of the event occurring.

In other words, hθ(x) = g(θ0 + θ1x1 + θ2x2) where x is the input vector and θ is the vector of parameters.

Source: [Session 7 Ml - logistic regression.pdf]
====================================================================================================
Question 7: What is classification?

Answer:
 Classification is a type of machine learning problem where the goal is to predict a category or label for a given data point. This could involve predicting binary outcomes (such as promoting an employee or not) or multi-class outcomes (like identifying if an email is spam or not spam).

In classification tasks, the algorithm learns patterns from the provided training data, which includes both input features and output labels. This learning helps the algorithm to make predictions for new, unseen data points. Examples of classification algorithms include Logistic Regression, Decision Trees, Support Vector Machines (SVM), and Naïve Bayes.

However, it's important to note that classification can be either supervised or unsupervised. In supervised classification, the training data includes both input features and output labels. In unsupervised classification, no labels are provided, and the algorithm groups data points based on similarity (such as clustering customers based on their purchasing behavior).

Sources:
1. Session 3 intro to ML.pdf, Chunk 21
2. Session 3 intro to ML.pdf, Chunk 14
3. Session 3 intro to ML.pdf, Chunk 18
====================================================================================================
Question 8: What is the difference between linear regression and logistic regression?

Answer:
 In the provided course materials, Linear Regression and Logistic Regression are both machine learning techniques, but they are used for different purposes.

Linear Regression is used to predict a continuous output variable. It models the relationship between the dependent variable and one or more independent variables using a linear equation. The goal is to find the best-fit line that minimizes the error between the predicted and actual values.

On the other hand, Logistic Regression is used when the dependent variable is categorical, such as predicting 'pass' or 'fail' in the example provided. It also uses a linear equation, but the output is a probability value between 0 and 1, and a threshold of 0.5 is typically used to classify the output as either 'pass' (1) or 'fail' (0).

While Linear Regression predicts a continuous outcome, Logistic Regression predicts a categorical outcome by applying a Sigmoid function to the linear equation, which maps the output to a probability value.

Sources:
1. Session 6 - Linear Regresssion.pdf | Chunk 0
2. Session 7 Ml -logistic regression.pdf | Chunk 2, Chunk 6
3. Session 7 Ml -logistic regression.pdf | Example section
====================================================================================================
Question 9: What is overfitting?

Answer:
 In the provided course materials, the term "overfitting" is not explicitly defined. However, based on the context, we can infer that overfitting occurs when a model is too complex for the data and begins to fit the noise or outliers instead of the underlying pattern. This results in a model that performs well on the training data but poorly on unseen data (e.g., validation or test data).

In logistic regression, overfitting can be prevented by using regularized cost functions, as mentioned in Source 3 (Session 7 Ml - logistic regression.pdf, Chunk 11). Regularization adds a penalty term to the cost function to discourage large parameter values, thus helping to prevent the model from fitting the noise in the data.

Sources:
1. Session 7 Ml -logistic regression.pdf
2. Session 6 - Linear Regresssion.pdf
3. Session 7 Ml -logistic regression.pdf
====================================================================================================
Question 10: What is reinforcement learning?

Answer:
 Reinforcement Learning (RL) is a type of Machine Learning where the model learns by interacting with an environment and receiving rewards or penalties. The goal is to learn a policy that maximizes the total reward over time. The model adjusts its behavior based on the feedback it receives from the environment. Examples of applications include teaching robots to walk, AI playing games like Chess and Go, and training agents to play video games. Algorithms used for reinforcement learning include Q-Learning, Deep Q Networks (DQN), and Proximal Policy Optimization (PPO). [Source 1: Session 3 intro to ML.pdf | Chunk 11]

In [22]:
answer, sources = generate_answer(
    "Who won the FIFA World Cup in 2022?"
)

print(answer)

 I couldn't find this information in the provided course materials as they focus on Artificial Intelligence and Machine Learning, not sports or world events.

### Evaluation

In [23]:
evaluation_questions = [
    "What is machine learning?",
    "What are the main types of machine learning?",
    "What is supervised learning?",
    "What is linear regression?",
    "What is the hypothesis function in linear regression?",
    "What is the cost function?",
    "What is multiple linear regression?",
    "What is logistic regression?",
    "What is the sigmoid function?",
    "What is classification?"
]

evaluation_results = []

for i, question in enumerate(evaluation_questions, start=1):

    answer, sources = generate_answer(question)

    evaluation_results.append({
        "question_id": i,
        "question": question,
        "answer": answer,
        "sources": ", ".join(
            sorted(set(source["source"] for source in sources))
        )
    })

print(f"Evaluated {len(evaluation_results)} questions.")

Evaluated 10 questions.

In [24]:
import pandas as pd

evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df[
    ["question_id", "question", "sources"]
]

,question_id,question,sources
0,1,What is machine learning?,Session 3 intro to ML.pdf
1,2,What are the main types of machine learning?,Session 3 intro to ML.pdf
2,3,What is supervised learning?,Session 3 intro to ML.pdf
3,4,What is linear regression?,Session 6 - Linear Regresssion.pdf
4,5,What is the hypothesis function in linear regr...,"Session 6 - Linear Regresssion.pdf, Session 7 ..."
5,6,What is the cost function?,"Session 6 - Linear Regresssion.pdf, Session 7 ..."
6,7,What is multiple linear regression?,Session 6 - Linear Regresssion.pdf
7,8,What is logistic regression?,Session 7 Ml -logistic regression.pdf
8,9,What is the sigmoid function?,Session 7 Ml -logistic regression.pdf
9,10,What is classification?,Session 3 intro to ML.pdf

In [25]:
for row in evaluation_results:
    print("=" * 100)
    print(f"Q{row['question_id']}: {row['question']}")
    print("\nAnswer:")
    print(row["answer"])
    print("\nSources:")
    print(row["sources"])

====================================================================================================
Q1: What is machine learning?

Answer:
 Machine Learning (ML) is a branch of Artificial Intelligence (AI) that focuses on developing systems capable of learning from data without being explicitly programmed. Instead of writing detailed instructions for every possible scenario, ML models analyze patterns in data to make intelligent decisions.

[Source 1: Session 3 intro to ML.pdf | Chunk 10]
[Source 2: Session 3 intro to ML.pdf | Chunk 9]
[Source 3: Session 3 intro to ML.pdf | Chunk 0]

Sources:
Session 3 intro to ML.pdf
====================================================================================================
Q2: What are the main types of machine learning?

Answer:
 The main types of Machine Learning (ML) are Supervised Learning and Unsupervised Learning, as mentioned in the provided course materials.

Supervised Learning involves training a model using labeled data (input-output pairs) such as predicting house prices based on features like size and location. Algorithms for Supervised Learning include Linear Regression, Decision Trees, Random Forest, Support Vector Machines (SVM), etc.

Unsupervised Learning, on the other hand, trains a model on unlabeled data, where the goal is to identify patterns and structures. An example of Unsupervised Learning is customer segmentation in marketing.

Sources:
1. Session 3 intro to ML.pdf, Chunk 10
2. Session 3 intro to ML.pdf, Chunk 9
3. Session 3 intro to ML.pdf, Chunk 7

Sources:
Session 3 intro to ML.pdf
====================================================================================================
Q3: What is supervised learning?

Answer:
 Supervised Learning is a type of Machine Learning where the model is trained using labeled data. The dataset consists of input-output pairs, meaning each input (features) has a corresponding correct output (label). The model learns the relationship between inputs and outputs, allowing it to make predictions on new data.

The process of supervised learning follows these steps:
1. Collect Data: A dataset with features (X) and labels (Y) is gathered.
2. Split the Data: The dataset is divided into Training Set (80%) and Testing Set (20%).
3. Choose an Algorithm: Depending on the problem, select a regression or classification algorithm.
4. Train the Model: The model learns from the training data by identifying patterns and relationships.
5. Evaluate the Model: Use the test data to check accuracy and performance.

[Source 1: Session 3 intro to ML.pdf | Chunk 12, Source 2: Session 3 intro to ML.pdf | Chunk 12, Source 3: Session 3 intro to ML.pdf | Chunk 10]

Sources:
Session 3 intro to ML.pdf
====================================================================================================
Q4: What is linear regression?

Answer:
 Linear Regression is a statistical method used to establish a relationship between two variables. The goal is to create a function, called 𝒉𝜽, which maps input data (the 𝑥′𝑠) to output data (the 𝑦′𝑠). This function is in the form of a straight line, similar to the equation of a line. Linear Regression helps predict the value of a dependent variable (𝑦′𝑠) based on one or more independent variables (𝑥′𝑠). This concept is also extended to multiple variables, known as "multivariate linear regression." The accuracy of the hypothesis function is measured by a cost function, which takes an average of all the results of the hypothesis with inputs from x's compared to the actual output y's.

Source(s):
1. Session 6 - Linear Regression.pdf | Chunk 0, Chunk 1, Chunk 5
2. https://www.slideshare.net/MohamedKhaled1988/machine-learning-session-6-linear-regression (Interactive Visualization of Linear Regression)

Sources:
Session 6 - Linear Regresssion.pdf
====================================================================================================
Q5: What is the hypothesis function in linear regression?

Answer:
 The hypothesis function in linear regression is a function that attempts to map the input data (x's) to the output data (y's), and it has the general form of an equation of a straight line. The function is denoted as 𝒉𝜽, and it includes an intercept (b) and a slope (m). The equation of the hypothesis function is given by y' = b + m*x'.

[Source 1: Session 6 - Linear Regresssion.pdf | Chunk 1]
[Source 2: Session 6 - Linear Regresssion.pdf | Chunk 0] (for definition of Linear Regression)

Sources:
Session 6 - Linear Regresssion.pdf, Session 7 Ml -logistic regression.pdf
====================================================================================================
Q6: What is the cost function?

Answer:
 The cost function is a measure that quantifies the error between the logistic regression model's predictions and the actual labels in the training data. It helps to minimize the error during training to find the optimal parameters (θ) for the model. As the sigmoid function used in logistic regression is a nonconvex function, it is converted to a convex function to ensure finding the global minimum.

Source(s):
1. Session 6 - Linear Regresssion.pdf | Chunk 3
2. Session 7 Ml -logistic regression.pdf | Chunk 8, Chunk 3

Sources:
Session 6 - Linear Regresssion.pdf, Session 7 Ml -logistic regression.pdf
====================================================================================================
Q7: What is multiple linear regression?

Answer:
 Multiple linear regression is a type of linear regression where the hypothesis function maps multiple input variables (also known as features) to a single output variable. This is also referred to as "multivariate linear regression". [Source 2, Chunk 2]

In multiple linear regression, the hypothesis function has the form of a straight line that takes multiple input variables into account. [Source 2, Chunk 1]

Sources:
1. Session 6 - Linear Regression.pdf
2. Session 6 - Linear Regression.pdf
3. Session 6 - Linear Regression.pdf

Sources:
Session 6 - Linear Regresssion.pdf
====================================================================================================
Q8: What is logistic regression?

Answer:
 Logistic Regression is a statistical modeling technique used for binary classification problems, where the outcome can have two possible results, such as pass/fail, 0/1, or yes/no. In the context provided, it is used to predict whether a student passes or fails an exam based on their study hours.

The logistic regression workflow consists of several steps:
1. Sigmoid Function: It defines the hypothesis hθ​(x), which outputs probabilities.
2. Cost Function: It measures how well the hypothesis fits the training data, guiding the optimization.
3. Gradient Descent: It optimizes the parameters θ to minimize the cost function.
4. Decision Boundary: It arises after training, showing where the model switches between classes (y=0 y = 0 y=0 and y=1 y = 1 y=1).

The decision boundary is graphically plotted as x1 + x2 = 3 in the example provided, where x1 and x2 represent the study hours and sleep hours, respectively.

Sources:
1. Session 7 Ml -logistic regression.pdf | Chunk 6
2. Session 7 Ml -logistic regression.pdf | Chunk 2
3. Session 7 Ml -logistic regression.pdf | Chunk 7

Sources:
Session 7 Ml -logistic regression.pdf
====================================================================================================
Q9: What is the sigmoid function?

Answer:
 The sigmoid function is a mathematical function used in logistic regression. It is defined as g(z) = 1 / (1 + e^-z), where z is a real number.

In the context of logistic regression, the hypothesis function hθ(x) is a linear combination of features x, weighted by the parameters θ. The resulting z value is compared to 0. If z is positive, the sigmoid function g(z) is greater than 0.5, and the hypothesis predicts y = 1. If z is negative, the sigmoid function g(z) is less than 0.5, and the hypothesis predicts y = 0.

Sources:
1. Session 7 Ml -logistic regression.pdf | Chunk 3
2. Session 7 Ml -logistic regression.pdf | Chunk 1
3. Session 7 Ml -logistic regression.pdf | Chunk 0

Sources:
Session 7 Ml -logistic regression.pdf
====================================================================================================
Q10: What is classification?

Answer:
 Classification is a type of machine learning problem where the goal is to predict a categorical output, also known as labels or classes. In classification, the outcome can have more than two categories or just two possible outcomes, known as binary classification.

For example, in the context of employee performance prediction, the goal is to classify whether an employee will be promoted or not promoted within a year based on their performance reviews, tenure, and skills. This is a binary classification problem.

Another example is medical test results, where the goal is to predict the presence or absence of a disease based on the results of various medical tests. This can also be a binary classification problem.

However, classification can also involve more than two categories. For instance, customer segmentation is an unsupervised task where customers are grouped into different segments based on their purchasing behavior, such as high spenders, frequent shoppers, or occasional buyers. This is an example of multi-class classification.

In addition, association rule learning, such as market basket analysis, is an unsupervised subfield of classification that identifies which products are frequently bought together in transactions to provide better product recommendations.

Some common algorithms used for classification include logistic regression, decision trees, support vector machine (SVM), and Naive Bayes.

Sources:
1. Session 3 intro to ML.pdf | Chunks 21, 14, 18
2. https://www.datacamp.com/community/tutorials/logistic-regression-scikit-learn#:~:text=Logistic%20regression%20is%20a%20classification,between%200%20and%201%20(inclusive).
3. https://scikit-learn.org/stable/modules/clustering.html
4. https://scikit-learn.org/stable/modules/generated/sklearn.association.APRIori.html

Sources:
Session 3 intro to ML.pdf

In [27]:
evaluation_df["relevance"] = ["Relevant"] * len(evaluation_df)

evaluation_df["grounded"] = ["Grounded"] * len(evaluation_df)

evaluation_df["failure_case"] = ["None"] * len(evaluation_df)

evaluation_df["mitigation"] = ["None"] * len(evaluation_df)

evaluation_df

,question_id,question,answer,sources,relevance,grounded,failure_case,mitigation
0,1,What is machine learning?,Machine Learning (ML) is a branch of Artifici...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
1,2,What are the main types of machine learning?,The main types of Machine Learning (ML) are S...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
2,3,What is supervised learning?,Supervised Learning is a type of Machine Lear...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
3,4,What is linear regression?,Linear Regression is a statistical method use...,Session 6 - Linear Regresssion.pdf,Relevant,Grounded,None,None
4,5,What is the hypothesis function in linear regr...,The hypothesis function in linear regression ...,"Session 6 - Linear Regresssion.pdf, Session 7 ...",Relevant,Grounded,None,None
5,6,What is the cost function?,The cost function is a measure that quantifie...,"Session 6 - Linear Regresssion.pdf, Session 7 ...",Relevant,Grounded,None,None
6,7,What is multiple linear regression?,Multiple linear regression is a type of linea...,Session 6 - Linear Regresssion.pdf,Relevant,Grounded,None,None
7,8,What is logistic regression?,Logistic Regression is a statistical modeling...,Session 7 Ml -logistic regression.pdf,Relevant,Grounded,None,None
8,9,What is the sigmoid function?,The sigmoid function is a mathematical functi...,Session 7 Ml -logistic regression.pdf,Relevant,Grounded,None,None
9,10,What is classification?,Classification is a type of machine learning ...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None

In [30]:
out_of_domain_question = "Who won the FIFA World Cup in 2022?"

answer, sources = generate_answer(
    out_of_domain_question
)

print("Question:", out_of_domain_question)
print("\nAnswer:")
print(answer)

print("\nSources:")
for source in sources:
    print("-", source["source"])

Question: Who won the FIFA World Cup in 2022?

Answer:
 I couldn't find this information in the provided course materials. The course material discusses Artificial Intelligence, Generative Models, Supervised Learning, Regression, and Classification, but there is no mention of the FIFA World Cup or its results from 2022. To find out who won the FIFA World Cup in 2022, you may want to check a reliable sports news source or the official FIFA website.

Sources:
- Session 3 intro to ML.pdf
- Session 3 intro to ML.pdf
- Session 3 intro to ML.pdf

In [31]:
evaluation_results.append({
    "question_id": 11,
    "question": out_of_domain_question,
    "answer": answer,
    "sources": ", ".join(
        sorted(set(source["source"] for source in sources))
    )
})

In [32]:
evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df

,question_id,question,answer,sources
0,1,What is machine learning?,Machine Learning (ML) is a branch of Artifici...,Session 3 intro to ML.pdf
1,2,What are the main types of machine learning?,The main types of Machine Learning (ML) are S...,Session 3 intro to ML.pdf
2,3,What is supervised learning?,Supervised Learning is a type of Machine Lear...,Session 3 intro to ML.pdf
3,4,What is linear regression?,Linear Regression is a statistical method use...,Session 6 - Linear Regresssion.pdf
4,5,What is the hypothesis function in linear regr...,The hypothesis function in linear regression ...,"Session 6 - Linear Regresssion.pdf, Session 7 ..."
5,6,What is the cost function?,The cost function is a measure that quantifie...,"Session 6 - Linear Regresssion.pdf, Session 7 ..."
6,7,What is multiple linear regression?,Multiple linear regression is a type of linea...,Session 6 - Linear Regresssion.pdf
7,8,What is logistic regression?,Logistic Regression is a statistical modeling...,Session 7 Ml -logistic regression.pdf
8,9,What is the sigmoid function?,The sigmoid function is a mathematical functi...,Session 7 Ml -logistic regression.pdf
9,10,What is classification?,Classification is a type of machine learning ...,Session 3 intro to ML.pdf
10,11,Who won the FIFA World Cup in 2022?,I couldn't find this information in the provi...,Session 3 intro to ML.pdf

In [34]:
evaluation_df["relevance"] = ["Relevant"] * 10 + ["Not Relevant"]

evaluation_df["grounded"] = ["Grounded"] * 10 + ["Not Grounded"]

evaluation_df["failure_case"] = (
    ["None"] * 10
    + ["Out-of-domain question"]
)

evaluation_df["mitigation"] = (
    ["None"] * 10
    + ["Return a fallback response when information is unavailable"]
)
evaluation_df

,question_id,question,answer,sources,relevance,grounded,failure_case,mitigation
0,1,What is machine learning?,Machine Learning (ML) is a branch of Artifici...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
1,2,What are the main types of machine learning?,The main types of Machine Learning (ML) are S...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
2,3,What is supervised learning?,Supervised Learning is a type of Machine Lear...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
3,4,What is linear regression?,Linear Regression is a statistical method use...,Session 6 - Linear Regresssion.pdf,Relevant,Grounded,None,None
4,5,What is the hypothesis function in linear regr...,The hypothesis function in linear regression ...,"Session 6 - Linear Regresssion.pdf, Session 7 ...",Relevant,Grounded,None,None
5,6,What is the cost function?,The cost function is a measure that quantifie...,"Session 6 - Linear Regresssion.pdf, Session 7 ...",Relevant,Grounded,None,None
6,7,What is multiple linear regression?,Multiple linear regression is a type of linea...,Session 6 - Linear Regresssion.pdf,Relevant,Grounded,None,None
7,8,What is logistic regression?,Logistic Regression is a statistical modeling...,Session 7 Ml -logistic regression.pdf,Relevant,Grounded,None,None
8,9,What is the sigmoid function?,The sigmoid function is a mathematical functi...,Session 7 Ml -logistic regression.pdf,Relevant,Grounded,None,None
9,10,What is classification?,Classification is a type of machine learning ...,Session 3 intro to ML.pdf,Relevant,Grounded,None,None
10,11,Who won the FIFA World Cup in 2022?,I couldn't find this information in the provi...,Session 3 intro to ML.pdf,Not Relevant,Not Grounded,Out-of-domain question,Return a fallback response when information is...

In [35]:
evaluation_path = PROJECT_DIR / "evaluation_results.csv"

evaluation_df.to_csv(evaluation_path, index=False)

print(f"Evaluation saved to: {evaluation_path}")

Evaluation saved to: d:\🎓 Project StudyMate — RAG-Powered University Assistant\evaluation_results.csv

In [36]:
import json

config = {
    "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
    "embedding_device": device,
    "vector_database": "ChromaDB",
    "collection_name": "studymate_documents",
    "chunk_size": 800,
    "chunk_overlap": 150,
    "retrieval_k": 3,
    "llm": "mistral"
}

config_path = (
    PROJECT_DIR
    / "backend"
    / "data"
    / "vector_store"
    / "config.json"
)

with open(config_path, "w") as f:
    json.dump(config, f, indent=4)

print(f"Config saved to: {config_path}")

Config saved to: d:\🎓 Project StudyMate — RAG-Powered University Assistant\backend\data\vector_store\config.json

In [37]:
print("Vector store:", VECTOR_DB_DIR)
print("Stored chunks:", collection.count())

Vector store: d:\🎓 Project StudyMate — RAG-Powered University Assistant\backend\data\vector_store
Stored chunks: 45